name: Publish

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: "Version type (minor or patch)"
        required: true
        type: choice
        options:
          - minor
          - patch

jobs:
  validate-publish-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Bump version and commit
        run: |
          npm version ${{ github.event.inputs.versionType }} -m "chore(release): bump to %s version"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
